import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";
import Footer from "@/components/ui/footer";

const poppins = localFont({
	src: [
		{
			path: "../public/fonts/Poppins-Regular.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "../public/fonts/Poppins-SemiBold.ttf",
			weight: "500",
			style: "normal",
		},
		{
			path: "../public/fonts/Poppins-Bold.ttf",
			weight: "700",
			style: "normal",
		},
	],
	variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${poppins.className}`}
      >
			  {children}
			  <Footer/>
      </body>
    </html>
  );
}
